"=================== VIM CONFIG ==========================
"
" Personal preference .vimrc file
" Maintained by Vincent Jacquel <eyesonly202@gmail.com>
"
"=================== 2011-2012  ==========================

" To start vim without using this .vimrc file, use:
" vim -u NORC
"
" To start vim without loading any .vimrc or plugins, use:
" vim -u NONE
" 


" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" ============== Pathogen Initialization ===============
" This loads all the plugins in ~/.vim/bundle
" Use tpope's pathogen plugin to manage all other plugins

"  runtime bundle/tpope-vim-pathogen/autoload/pathogen.vim
"  call pathogen#infect()
"  call pathogen#helptags()

if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
" source ~/.vim/vimrc


" ================ Lead remapping ====================

let mapleader = ","

" ================ General Config ====================

set number                  " Set line numbering
set numberwidth=5
set ruler                   " Show the cursor position all the time
set encoding=utf-8          " Set encoding
syntax on                   " Turn on syntax highlighting
set showcmd                 " Show (partial) command in status line.
set showmode                " Show current mode down the bottom
set ch=2                    " command line height

set history=1000            " Remember more commands and search history

" ================ Indentation ======================

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set nowrap                            " Don't wrap lines
set linebreak                         " Wrap lines at convenient points
set list listchars=tab:\ \ ,trail:·   " display tabs and trailing spaces visually

filetype plugin on
filetype indent on

" ================== Search Settings =================

set incsearch                 " Find the next match as we type the search
set hlsearch                  " Hilight searches by default
" set nohlsearch                " don't highlight searches
set showmatch                 " Show matching brackets/braces
set mat=5                     " Duration to show matching brace (1/10 sec)
set viminfo='100,f1           " Save up to 100 marks, enable capital marks
set ignorecase                " Ignore case when searching
set smartcase
set visualbell                " Shut the fuck up

nnoremap <leader><space> :noh<cr>         " clear out a search by typing ,space
map <silent> <leader>qs <Esc>:noh<CR> " Clear last search (,qs)
" map <silent> <leader>qs <Esc>:let @/ = ""<CR>


" ================ Folds ============================

set foldmethod=indent "fold based on indent
set foldnestmax=3 "deepest fold is 3 levels
set nofoldenable "dont fold by default


" ================ Completion =======================

set wildmode=list:longest,list:full
set wildmenu                                                       " enable ctrl-n and ctrl-p to scroll thru matches
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*,*~ " stuff to ignore when tab completing
set wildignore+=*vim/backups*


" ================ Scrolling ========================

set scrolloff=8 "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1


" ================ Status bar ========================
set laststatus=2


" Without setting this, ZoomWin restores windows in a way that causes
" equalalways behavior to be triggered the next time CommandT is used.
" This is likely a bludgeon to solve some other issue, but it works
set noequalalways


" Command-T configuration
let g:CommandTMaxHeight=20


" ZoomWin configuration
map <Leader><Leader> :ZoomWin<CR>


" CTags
map <Leader>rt :!ctags --extra=+f -R *<CR><CR>
map <C-\> :tnext<CR>


" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif


function s:setupWrapping()
  set wrap
  set wrapmargin=2
  set textwidth=72
endfunction

function s:setupMarkup()
  call s:setupWrapping()
  map <buffer> <Leader>p :Hammer<CR>
endfunction


" Thorfile, Rakefile, Vagrantfile and Gemfile are Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru}    set ft=ruby


" md, markdown, and mk are markdown and define buffer-local preview
au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} call s:setupMarkup()


" add json syntax highlighting
au BufNewFile,BufRead *.json set ft=javascript
au BufRead,BufNewFile *.txt call s:setupWrapping()


" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" load the plugin and indent settings for the detected filetype
filetype plugin indent on

" Opens an edit command with the path of the currently edited file filled in
" Normal mode: <Leader>e
map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

" Opens a tab edit command with the path of the currently edited file filled in
" Normal mode: <Leader>t
map <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>

" Inserts the path of the currently edited file into a command
" Command mode: Ctrl+P
cmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

" Unimpaired configuration
" Bubble single lines
nmap <C-Up> [e
nmap <C-Down> ]e
" Bubble multiple lines
vmap <C-Up> [egv
vmap <C-Down> ]egv

" Enable syntastic syntax checking
let g:syntastic_enable_signs=1
let g:syntastic_quiet_warnings=1

" gist-vim defaults
if has("mac")
  let g:gist_clip_command = 'pbcopy'
elseif has("unix")
  let g:gist_clip_command = 'xclip -selection clipboard'
endif
let g:gist_detect_filetype = 1
let g:gist_open_browser_after_post = 1

" Use modeline overrides
set modeline
set modelines=10

" ================ Default colorscheme ========================
color desert

" ================ Directories for swp files ========================
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Turn off jslint errors by default
let g:JSLintHighlightErrorLine = 0

" MacVIM shift+arrow-keys behavior (required in .vimrc)
let macvim_hig_shift_movement = 1

" % to bounce from do to end etc.
runtime! macros/matchit.vim

" ================ NERDTree configuration ========================

map <F12> :NERDTreeToggle<CR>
"let g:NERDTreeWinPos = "right"
"let g:NERDTreeWinSize=33

let NERDChristmasTree = 1               " enable nice colors
let NERDTreeHighlightCursorline = 1     " Make it easy to see where we are
let NERDTreeMinimalUI = 0
let NERDTtreeShowBookmarks = 1          " Make Bookmarks visible
let NERDTreeShowHidden = 1              " Show hidden files
let NERDTreeHijackNetrw = 0             " Don't hijack NETRW
let NERDTreeIgnore=['\.pyc$', '\.rbc$', '\~$', '\.$']

let NERDTreeDirArrows = 1
let NERDTreeWinsize = 30


" ================ Function keys shortcuts  ========================

set pastetoggle=<F2>        " kill theses indent when pasting !!!!
set splitbelow              " split new horizontal window below current
set splitright              " split new vertical windows to the right
set autoread                " Reload files changed outside vim

nmap <F1> <Esc>             " No Help, please
map <F1> <Esc>
map! <F1> <Esc>
if has("gui_running")
  map <F2> :Fancy<CR>
endif
map <F3> :cnext<CR>
map <F4> :cc<CR>
map <F5> :cprev<CR>
nmap <silent> <F6> :if &previewwindow<Bar>pclose<Bar>elseif exists(':Gstatus')<Bar>exe 'Gstatus'<Bar>else<Bar>ls<Bar>endif<CR>
nmap <silent> <F7> :if exists(':Glcd')<Bar>exe 'Glcd'<Bar>elseif exists(':Rlcd')<Bar>exe 'Rlcd'<Bar>else<Bar>lcd %:h<Bar>endif<CR>
map <F8> :wa<Bar>make<CR>
map <F9> :Run<CR>
map <silent> <F10> :let tagsfile = tempname()\|silent exe "!ctags -f ".tagsfile." \"%\""\|let &l:tags .= "," . tagsfile\|unlet tagsfile<CR>
map <silent> <F11> :if exists(":BufExplorer")<Bar>exe "BufExplorer"<Bar>else<Bar>buffers<Bar>endif<CR>
map <C-F4> :bdelete<CR>

inoremap jj <ESC>           " exit to normal mode with jj
nnoremap Y  y$              " yanks until the end of line (lazy remapping!)

" indent/unident block (,]) (,[)
nnoremap <leader>] >i{<CR>
nnoremap <leader>[ <i{<CR>


"  ================ Section: Visual  ========================

" Switch syntax highlighting on, when the terminal has colors
if (&t_Co > 2 || has("gui_running")) && has("syntax")
  function! s:initialize_font()
    if exists("&guifont")
      if has("mac")
        set guifont=Monaco:h12
      elseif has("unix")
        if &guifont == ""
          set guifont=bitstream\ vera\ sans\ mono\ 11
        endif
      elseif has("win32")
        set guifont=Consolas:h11,Courier\ New:h10
      endif
    endif
  endfunction
endif


" ================ Strip all trailing whitespace in file  ====================

function! StripWhitespace ()
  exec ':%s/ \+$//gc'
endfunction

map ,s :call StripWhitespace ()<CR>

" ================ Leader shortcut for Rails commands  ====================

map <Leader>m :Rmodel
map <Leader>c :Rcontroller
map <Leader>v :Rview
map <Leader>u :Runittest
map <Leader>f :Rfunctionaltest
map <Leader>tm :RTmodel
map <Leader>tc :RTcontroller
map <Leader>tv :RTview
map <Leader>tu :RTunittest
map <Leader>tf :RTfunctionaltest
map <Leader>sm :RSmodel
map <Leader>sc :RScontroller
map <Leader>sv :RSview
map <Leader>su :RSunittest
map <Leader>sf :RSfunctionaltest 

" Opens an edit command with the path of the currently edited file filled in
" Normal mode: <Leader>e
map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

" Opens a tab edit command with the path of the currently edited file filled
"  in Normal mode: <Leader>t
map <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>

" Inserts the path of the currently edited file into a command
" Command mode: Ctrl+P
cmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

" Duplicate a selection
" Visual mode: D
vmap D y'>p

" Forced use the damn hjkl keys
" map <up> <nop>
" map <down> <nop>
" map <left> <nop>
" map <right> <nop>
" nnoremap <up> <nop>
" nnoremap <down> <nop>
" nnoremap <left> <nop>
" nnoremap <right> <nop>
" inoremap <up> <nop>
" inoremap <down> <nop>
" inoremap <left> <nop>
" inoremap <right> <nop>
nnoremap j gj
nnoremap k gk


" Easy window navigation
map <c-h> <c-w>h
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
nnoremap <leader>w <C-w>v<C-w>l

" Use ,d (or ,dd or ,dj or 20,dd) to delete a line without adding it to the
" yanked stack (also, in visual mode)
nmap <silent> <leader>d "_d
vmap <silent> <leader>d "_d

" Yank/paste to the OS clipboard with ,y and ,p
nmap <leader>y "+y
nmap <leader>Y "+yy
nmap <leader>p "+p
nmap <leader>P "+P

" Quick alignment of text
nmap <leader>al :left<CR>
nmap <leader>ar :right<CR>
nmap <leader>ac :center<CR>

" new tab
map <C-t><C-t> :tabnew<CR>
" close tab
map <C-t><C-w> :tabclose<CR> 

" ================ NERDCommnenter plugin ====================

let NERDDefaultNesting = 0
let NERDRemoveExtraSpaces = 1
let NERDSpacesDelims = 1

" ==================== Ruby plugin ==========================

let ruby_operators = 1
let g:rails_statusline = 0


" ========================= Tags ============================

set tags=./tags;

function! s:RebuildTagsFile()
  !ctags -R --exclude=coverage --exclude=files --excludes=public --exclude=log --exclude=tmp --exclude=vendor *
endfunction

" ========================== Faster split resizing (+,-)=====

if bufwinnr(1)
    map + <C-W>+
    map - <C-W>-
endif

" ========================= smart utilities =================
"
" Sudo write (,W)
noremap <leader>W :w !sudo tee %<CR>

" Remap :W to :w
command W w
